default:
	  javac cpsc2150/extendedConnectX/models/*.java cpsc2150/extendedConnectX/controllers/*.java

run:
	  java cpsc2150/extendedConnectX/models/ConnectXApp

clean:
	  rm -f cpsc2150/extendedConnectX/models/*.class